version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
