services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - backend
      - db
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: noteref-dev
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    volumes:
      - ./server:/go/src/github.com/StudioPrimo/noteref

  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: primo
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  db_data:
