FROM golang:1.22.4-alpine

RUN apk update && apk add git

WORKDIR /go/src/StudioPrimo/noteref
COPY . .

EXPOSE 8080

RUN go install github.com/air-verse/air@latest
RUN go mod download

CMD [ "air", "-c", ".air.toml" ]