# Build stage
FROM golang:1.22-buster AS build

WORKDIR /go/src/github.com/Doer-org/glyph

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

# Install air for hot-reloading
RUN go install github.com/cosmtrek/air@latest

# Expose necessary port
EXPOSE 8080

# Command to start air
CMD ["air", "-c", ".air.toml"]

# Deploy stage
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go/src/github.com/Doer-org/glyph /glyph

COPY --from=build /go/bin/air /usr/local/bin/air

WORKDIR /glyph

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["air", "-c", ".air.toml"]
