FROM golang:1.22

WORKDIR /go/src/github.com/StudioPrimo/noteref

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

=RUN go install github.com/cosmtrek/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go/src/github.com/StudioPrimo/noteref /noteref

COPY --from=build /go/bin/air /usr/local/bin/air

WORKDIR /noteref

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["air", "-c", ".air.toml"]
