services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../frontend:/app
    working_dir: /app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - backend
      - database
