services:
  frontend:
    build: ../frontend
    ports:
      - '3000:3000'
    volumes:
      - ../frontend:/app
    working_dir: /app/src
    command: /bin/sh -c "npm install && tail -f /dev/null"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - backend
      - database