services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - '3000:3000'
    working_dir: /app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENVIRONMENT=${ENVIRONMENT}
    tty: true
    depends_on:
      - backend
      - database
    volumes:
      - ../frontend:/app
    command: sh -c "npm i && npm run build && if [ \"$ENVIRONMENT\" != \"dev\" ]; then npm run start; fi"