services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - '3000:3000'
    working_dir: /app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - backend
      - database
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run build && npm run start"