name: Go

on:
  push:
    paths:
     - .github/**
     - backend/**
    branches: [ "dev","main" ]
  pull_request:
    paths:
     - .github/**
     - backend/**
    branches: [ "dev","main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.4

    - name: Build
      run: cd backend && go build -v ./...

    - name: Test
      run: |
       cd backend && go test -v ./...